name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/Bronze.png
    - assets/Silver.png
    - assets/Gold.png
    - assets/Trophy.png
    - assets/virat.png
    - assets/versus.png
    - assets/Bumrah.png
    - assets/schedule_diagram/team8.png
    - assets/schedule_diagram/team4.png
    - assets/schedule_diagram/team4f.png
    - assets/schedule_diagram/team2f.png
    - assets/Cricket.png
    - assets/football.png
    - assets/sports.png
    - assets/label_style.png
